name: google_maps_places_platform_interface
description: A common platform interface for the google_maps_places plugin.
repository: https://github.com/flutter/plugins/tree/main/packages/google_maps_places/google_maps_places_platform_interface
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+google_maps_places%22
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 0.0.1

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
