// Copyright 2013 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
// Autogenerated from Pigeon (v4.2.5), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

enum TypeFilter {
  address,
  cities,
  establishment,
  geocode,
  regions,
  all,
}

enum PlaceType {
  accounting,
  administrativeAreaLevel1,
  administrativeAreaLevel2,
  administrativeAreaLevel3,
  administrativeAreaLevel4,
  administrativeAreaLevel5,
  airport,
  amusementPark,
  aquarium,
  archipelago,
  artGallery,
  atm,
  bakery,
  bank,
  bar,
  beautySalon,
  bicycleStore,
  bookStore,
  bowlingAlley,
  busStation,
  cafe,
  campground,
  carDealer,
  carRental,
  carRepair,
  carWash,
  casino,
  cemetery,
  church,
  cityHall,
  clothingStore,
  colloquialArea,
  continent,
  convenienceStore,
  country,
  courthouse,
  dentist,
  departmentStore,
  doctor,
  drugstore,
  electrician,
  electronicsStore,
  embassy,
  establishment,
  finance,
  fireStation,
  floor,
  florist,
  food,
  funeralHome,
  furnitureStore,
  gasStation,
  generalContractor,
  geocode,
  groceryOrSupermarket,
  gym,
  hairCare,
  hardwareStore,
  health,
  hinduTemple,
  homeGoodsStore,
  hospital,
  insuranceAgency,
  intersection,
  jewelryStore,
  laundry,
  lawyer,
  library,
  lightRailStation,
  liquorStore,
  locality,
  localGovernmentOffice,
  locksmith,
  lodging,
  mealDelivery,
  mealTakeaway,
  mosque,
  movieRental,
  movieTheater,
  movingCompany,
  museum,
  naturalFeature,
  neighborhood,
  nightClub,
  other,
  painter,
  park,
  parking,
  petStore,
  pharmacy,
  physiotherapist,
  placeOfWorship,
  plumber,
  plusCode,
  pointOfInterest,
  police,
  political,
  postalCode,
  postalCodePrefix,
  postalCodeSuffix,
  postalTown,
  postBox,
  postOffice,
  premise,
  primarySchool,
  realEstateAgency,
  restaurant,
  roofingContractor,
  room,
  route,
  rvPark,
  school,
  secondarySchool,
  shoeStore,
  shoppingMall,
  spa,
  stadium,
  storage,
  store,
  streetAddress,
  streetNumber,
  sublocality,
  sublocalityLevel1,
  sublocalityLevel2,
  sublocalityLevel3,
  sublocalityLevel4,
  sublocalityLevel5,
  subpremise,
  subwayStation,
  supermarket,
  synagogue,
  taxiStand,
  touristAttraction,
  townSquare,
  trainStation,
  transitStation,
  travelAgency,
  university,
  veterinaryCare,
  zoo,
}

class LatLng {
  LatLng({
    this.latitude,
    this.longitude,
  });

  double? latitude;
  double? longitude;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['latitude'] = latitude;
    pigeonMap['longitude'] = longitude;
    return pigeonMap;
  }

  static LatLng decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return LatLng(
      latitude: pigeonMap['latitude'] as double?,
      longitude: pigeonMap['longitude'] as double?,
    );
  }
}

class LatLngBounds {
  LatLngBounds({
    this.southwest,
    this.northeast,
  });

  LatLng? southwest;
  LatLng? northeast;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['southwest'] = southwest?.encode();
    pigeonMap['northeast'] = northeast?.encode();
    return pigeonMap;
  }

  static LatLngBounds decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return LatLngBounds(
      southwest: pigeonMap['southwest'] != null
          ? LatLng.decode(pigeonMap['southwest']!)
          : null,
      northeast: pigeonMap['northeast'] != null
          ? LatLng.decode(pigeonMap['northeast']!)
          : null,
    );
  }
}

class FindAutocompletePredictionsRequest {
  FindAutocompletePredictionsRequest({
    required this.query,
    this.locationBias,
    this.locationRestriction,
    this.origin,
    this.countries,
    this.typeFilter,
    this.refreshToken,
  });

  String query;
  LatLngBounds? locationBias;
  LatLngBounds? locationRestriction;
  LatLng? origin;
  List<String?>? countries;
  List<int?>? typeFilter;
  bool? refreshToken;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['query'] = query;
    pigeonMap['locationBias'] = locationBias?.encode();
    pigeonMap['locationRestriction'] = locationRestriction?.encode();
    pigeonMap['origin'] = origin?.encode();
    pigeonMap['countries'] = countries;
    pigeonMap['typeFilter'] = typeFilter;
    pigeonMap['refreshToken'] = refreshToken;
    return pigeonMap;
  }

  static FindAutocompletePredictionsRequest decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return FindAutocompletePredictionsRequest(
      query: pigeonMap['query']! as String,
      locationBias: pigeonMap['locationBias'] != null
          ? LatLngBounds.decode(pigeonMap['locationBias']!)
          : null,
      locationRestriction: pigeonMap['locationRestriction'] != null
          ? LatLngBounds.decode(pigeonMap['locationRestriction']!)
          : null,
      origin: pigeonMap['origin'] != null
          ? LatLng.decode(pigeonMap['origin']!)
          : null,
      countries: (pigeonMap['countries'] as List<Object?>?)?.cast<String?>(),
      typeFilter: (pigeonMap['typeFilter'] as List<Object?>?)?.cast<int?>(),
      refreshToken: pigeonMap['refreshToken'] as bool?,
    );
  }
}

class AutocompletePrediction {
  AutocompletePrediction({
    this.distanceMeters,
    required this.fullText,
    required this.placeId,
    required this.placeTypes,
    required this.primaryText,
    required this.secondaryText,
  });

  int? distanceMeters;
  String fullText;
  String placeId;
  List<int?> placeTypes;
  String primaryText;
  String secondaryText;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['distanceMeters'] = distanceMeters;
    pigeonMap['fullText'] = fullText;
    pigeonMap['placeId'] = placeId;
    pigeonMap['placeTypes'] = placeTypes;
    pigeonMap['primaryText'] = primaryText;
    pigeonMap['secondaryText'] = secondaryText;
    return pigeonMap;
  }

  static AutocompletePrediction decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return AutocompletePrediction(
      distanceMeters: pigeonMap['distanceMeters'] as int?,
      fullText: pigeonMap['fullText']! as String,
      placeId: pigeonMap['placeId']! as String,
      placeTypes: (pigeonMap['placeTypes'] as List<Object?>?)!.cast<int?>(),
      primaryText: pigeonMap['primaryText']! as String,
      secondaryText: pigeonMap['secondaryText']! as String,
    );
  }
}

class FindAutocompletePredictionsResponse {
  FindAutocompletePredictionsResponse({
    required this.results,
  });

  List<AutocompletePrediction?> results;

  Object encode() {
    final Map<Object?, Object?> pigeonMap = <Object?, Object?>{};
    pigeonMap['results'] = results;
    return pigeonMap;
  }

  static FindAutocompletePredictionsResponse decode(Object message) {
    final Map<Object?, Object?> pigeonMap = message as Map<Object?, Object?>;
    return FindAutocompletePredictionsResponse(
      results: (pigeonMap['results'] as List<Object?>?)!.cast<AutocompletePrediction?>(),
    );
  }
}

class _GoogleMapsPlacesApiCodec extends StandardMessageCodec{
  const _GoogleMapsPlacesApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is AutocompletePrediction) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else 
    if (value is FindAutocompletePredictionsRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else 
    if (value is FindAutocompletePredictionsResponse) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else 
    if (value is LatLng) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else 
    if (value is LatLngBounds) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else 
{
      super.writeValue(buffer, value);
    }
  }
  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128:       
        return AutocompletePrediction.decode(readValue(buffer)!);
      
      case 129:       
        return FindAutocompletePredictionsRequest.decode(readValue(buffer)!);
      
      case 130:       
        return FindAutocompletePredictionsResponse.decode(readValue(buffer)!);
      
      case 131:       
        return LatLng.decode(readValue(buffer)!);
      
      case 132:       
        return LatLngBounds.decode(readValue(buffer)!);
      
      default:      
        return super.readValueOfType(type, buffer);
      
    }
  }
}

class GoogleMapsPlacesApi {
  /// Constructor for [GoogleMapsPlacesApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  GoogleMapsPlacesApi({BinaryMessenger? binaryMessenger}) : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _GoogleMapsPlacesApiCodec();

  Future<FindAutocompletePredictionsResponse> findAutocompletePredictions(FindAutocompletePredictionsRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.GoogleMapsPlacesApi.findAutocompletePredictions', codec, binaryMessenger: _binaryMessenger);
    final Map<Object?, Object?>? replyMap =
        await channel.send(<Object?>[arg_request]) as Map<Object?, Object?>?;
    if (replyMap == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyMap['error'] != null) {
      final Map<Object?, Object?> error = (replyMap['error'] as Map<Object?, Object?>?)!;
      throw PlatformException(
        code: (error['code'] as String?)!,
        message: error['message'] as String?,
        details: error['details'],
      );
    } else if (replyMap['result'] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyMap['result'] as FindAutocompletePredictionsResponse?)!;
    }
  }
}
