name: camera_windows
description: A  Flutter plugin for getting information about and controlling the camera on Windows.
version: 0.0.1
homepage: TBD
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    implements: camera
    platforms:
      windows:
        pluginClass: CameraWindows

dependencies:
  #camera_platform_interface: ^2.1.0
  camera_platform_interface: 
    path: ../camera_platform_interface/
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
