name: google_maps_places_example
description: Demonstrates how to use the google_maps_places plugin.
publish_to: "none"

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_maps_places:
    path: ../

dev_dependencies:
  build_runner: 2.1.11
  flutter_driver:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
